#!/usr/bin/env python3

from pathlib import Path
from sys import argv

if len(argv) != 4:
	print("Usage: ./replace [PATH] [OLDPATTERN] [NEWPATTERN]")
	exit()

path = argv[1]
oldPattern = argv[2]
newPattern = argv[3]

if Path.exists(Path(path)):
	for i in Path.rglob(Path(path), oldPattern+'*'):
		fullPath = i.parent.absolute()
		rest = str(i).split(oldPattern, 1)[1]
		newPath = i.parent.absolute() / Path(newPattern + rest)
		i.rename(newPath)
		data = (newPath.read_text()).replace(oldPattern, newPattern)
		newPath.write_text(data)
else:
	print("Given path does not exist")
	exit()
